name: Deployment SPA to github pages
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./portfolio-ui
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy page
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://${github_token}@github.com/portfolio
        npm run deploy
      env:
        github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
